Repository FRONTENDSCHOOL5/final-24-Susumarket, pull requests merged in 2023-07, with the labels that each got.

#170 Feat: API 파일 추가
  src/API/commentAPI.js
  src/API/imgUploadAPI.js
  src/API/likeAPI.js
  src/API/loginAPI.js
  src/API/postAPI.js
  src/API/productAPI.js
  src/API/profileAPI.js
  src/API/searchAPI.js
  src/API/signupAPI.js
  src/API/validationAPI.js
Labels: feat

#171 Fix: CustomAxios import 추가 및 ProductAPI product 인자 추가
  src/API/commentAPI.js
  src/API/imgUploadAPI.js
  src/API/likeAPI.js
  src/API/loginAPI.js
  src/API/postAPI.js
  src/API/productAPI.js
  src/API/profileAPI.js
  src/API/searchAPI.js
  src/API/signupAPI.js
  src/API/validationAPI.js
Labels: fix

#173 Fix: post API export 추가
  src/API/postAPI.js
Labels: fix

#178 175 refactoring loginemail product 페이지
  src/API/imgUploadAPI.js
  src/API/loginAPI.js
  src/API/productAPI.js
  src/pages/feed/product/productDetail/ProductDetail.jsx
  src/pages/feed/product/productEdit/ProductEdit.jsx
  src/pages/feed/product/productUpload/ProductUpload.jsx
  src/pages/login/loginEmail/LoginEmail.jsx
Labels: refactoring

#180 177 refactor postupload postdetail postedit register 페이지
  src/API/commentAPI.js
  src/API/imgUploadAPI.js
  src/API/postAPI.js
  src/API/profileAPI.js
  src/pages/feed/post/postDetail/PostDetail.jsx
  src/pages/feed/post/postEdit/PostEdit.jsx
  src/pages/feed/post/postEdit/postEdit.style.js
  src/pages/feed/post/postUpload/PostUpload.jsx
  src/pages/feed/post/postUpload/postUpload.style.js
  src/pages/signup/profileSetting/ProfileSetting.jsx
  src/pages/signup/profileSetting/profileSetting.style.js
  src/pages/signup/userAccount/UserAccount.jsx
  src/pages/signup/userAccount/UserAccount.style.js
Labels: fix, feat
