Repository FRONTENDSCHOOL5/final-24-Susumarket, pull requests merged in 2023-08, with the labels that each got.

#187 184 refactoring register post 페이지
  src/pages/feed/post/postDetail/PostDetail.jsx
  src/pages/feed/post/postEdit/PostEdit.container.jsx
  src/pages/feed/post/postEdit/PostEdit.jsx
  src/pages/feed/post/postEdit/PostEdit.presenter.jsx
  src/pages/feed/post/postUpload/PostUpload.container.jsx
  src/pages/feed/post/postUpload/PostUpload.jsx
  src/pages/feed/post/postUpload/PostUpload.presenter.jsx
  src/pages/signup/profileSetting/ProfileSetting.container.jsx
  src/pages/signup/profileSetting/ProfileSetting.presenter.jsx
  src/pages/signup/userAccount/UserAccount.jsx
Labels: refactoring, fix, feat

#188 Refactoring: router 설정
  src/routes/Router.jsx
Labels: feat

#189 182 refactor search follow following 페이지
  src/components/commons/menuBar/MenuBar.jsx
  src/components/commons/userInfo/userInfo.style.js
  src/pages/chat/chatList/chatList.style.js
  src/pages/feed/search/Search.jsx
  src/pages/feed/search/SearchList.jsx
  src/pages/profile/follow/followers/Followers.jsx
  src/pages/profile/follow/followers/followerList.style.js
  src/pages/profile/follow/followers/followers.style.js
  src/pages/profile/follow/following/Following.jsx
  src/pages/profile/follow/following/following.style.js
  src/pages/profile/follow/following/followingList.style.js
Labels: refactoring, fix, feat

#196 Refactor: 팔로우리스트 중복출력 해결, useCallback 최적화
  src/pages/profile/follow/followers/Followers.jsx
  src/pages/profile/follow/following/Following.jsx
Labels: bug, refactoring
