Repository FRONTENDSCHOOL5/final-24-Susumarket, pull requests merged in 2023-06, with the labels that each got.

#4 Feat: MenuBar공통 컴포넌트추가
  src/components/commons/menuBar/MenuBar.jsx
  src/components/commons/menuBar/MenuBarStyle.js
Labels: feat

#8 Feat: DateFormat 공통컴포넌트 추가
  src/components/commons/dateFormat/DateFormat.jsx
Labels: feat

#15 Feat: TopButton 컴포넌트 추가
  src/components/commons/topButton/TopButton.jsx
Labels: feat

#17 Feat: ConfirmModal 공통 컴포넌트 추가
  src/components/commons/confirmModal/confirmModal.jsx
Labels: feat

#19 Feat: chat 페이지 추가
  src/pages/chat/chatList/ChatList.jsx
  src/pages/chat/chatList/chatList.style.js
  src/pages/chat/chatRoom/ChatRoom.jsx
  src/pages/chat/chatRoom/ChatRoom.style.js
Labels: feat

#23 fix: dataInput 변경
  src/components/commons/dataInput/dataInput.jsx
Labels: fix

#25 Style 변수명 변경
  src/components/commons/confirmModal/confirmModal.jsx
Labels: etc

#26 Feat: Context API UserProvider, ModalProvider 추가
  src/App.js
Labels: feat

#27 Feat: MenuBar 라우터설정
  src/routes/Router.jsx
Labels: feat

#30 Feat: CustomAxios 기능 추가
  src/library/customAxios.js
Labels: feat

#33 Fix: UserContext Provider에 account, setAccount 추가 수정
  src/App.js
Labels: fix

#36 18 feat 회원가입 page 추가
  src/pages/signup/profileSetting/ProfileSetting.jsx
  src/pages/signup/userAccount/UserAccount.jsx
Labels: feat

#35 Fix: CustomAxios headers Authorization 수정
  src/library/customAxios.js
Labels: fix

#38 Fix: ErrorMessage 기존 코드에서 common component에서 import하는 방법으로 수정
  src/pages/signup/profileSetting/ProfileSetting.jsx
  src/pages/signup/userAccount/UserAccount.jsx
Labels: fix

#46 18 feat 회원가입 page 추가
  src/pages/signup/profileSetting/ProfileSetting.jsx
  src/pages/signup/userAccount/UserAccount.jsx
Labels: feat

#50 Comment: 회원가입 주석 추가
  src/pages/signup/profileSetting/ProfileSetting.jsx
  src/pages/signup/userAccount/UserAccount.jsx
Labels: etc

#51 Feat: 회원가입 시 로그인 페이지로 이동하도록 수정
  src/pages/signup/profileSetting/ProfileSetting.jsx
Labels: etc

#54 Fix: account, accessToken 초기값을 localstorage에서 불러올 수 있도록 수정
  src/App.js
Labels: fix

#56 Feat: Router 로그인 분기 처리 추가
  src/routes/Router.jsx
Labels: feat

#60 Feat: ProfileDetail 페이지 ProfileInfo 컴포넌트 마크업 및 스타일 추가
  src/components/units/profile/profileInfo/ProfileInfo.jsx
  src/components/units/profile/profileInfo/ProfileInfo.styles.js
Labels: feat

#62 Feat, Fix: search 페이지 마크업 스타일추가, /search 이동시 홈버튼 활성화되도록 수정
  src/components/commons/menuBar/MenuBar.jsx
  src/pages/feed/search/Search.jsx
  src/pages/feed/search/SearchList.jsx
  src/pages/feed/search/search.style.js
  src/pages/feed/search/searchList.style.js
Labels: chore, fix, feat

#65 Fix: SetIsOpenConfirmModal을 setIsOpenConfirmModal로 수정
  src/components/commons/confirmModal/confirmModal.jsx
Labels: fix

#64 Feat: PostUpload 마크업 추가, 스타일 적용, textarea height 자동조절 코드 추가
  src/pages/feed/post/postUpload/PostUpload.jsx
Labels: feat

#69 Style: GlobalStyle 수정
  src/GlobalStyle.js
Labels: fix

#66 Feat: 61 feat profiledetail 페이지 profileproduct 컴포넌트 마크업 및 UI 추가 및 ProfileInfo 스타일 수정
  src/components/commons/topHeader/ProfileTopHeader.jsx
  src/components/commons/topHeader/TopHeader.jsx
  src/components/units/profile/ProfileProduct/ProfileProduct.jsx
  src/components/units/profile/ProfileProduct/ProfileProduct.styles.js
  src/components/units/profile/ProfileProduct/ProfileProductList.jsx
  src/components/units/profile/profileInfo/ProfileInfo.styles.js
Labels: fix, feat

#70 Fix: ProfuleInfoButtonWrapper에서 ProfileInfoButtonWrapper로 styled-compoents 명 오타 수정
  src/components/units/profile/profileInfo/ProfileInfo.jsx
Labels: fix

#78 76 feat postupload 페이지 구현
  src/pages/feed/post/postUpload/PostUpload.jsx
Labels: feat

#79 58 feat productupload 페이지 마크업
  src/pages/feed/product/productUpload/ProductUpload.jsx
  src/pages/feed/product/productUpload/productUpload.style.js
Labels: fix

#81 Feat: Search페이지 검색기능 추가
  src/components/commons/topHeader/SearchTopHeader.jsx
  src/pages/feed/search/Search.jsx
  src/pages/feed/search/SearchList.jsx
  src/pages/feed/search/search.style.js
  src/pages/feed/search/searchList.style.js
Labels: fix, feat

#84 Feat: Post Edit 페이지 마크업 추가, 추후 수정 가능
  src/pages/feed/post/postEdit/PostEdit.jsx
Labels: feat

#88 Feat: search페이지에 디바운스 패턴 적용
  src/library/useDebounce.js
  src/pages/feed/search/Search.jsx
Labels: feat

#96 89 feat 팔로우 팔로잉 페이지 마크업 구현
  src/pages/feed/search/search.style.js
  src/pages/profile/follow/followers/FollowerList.jsx
  src/pages/profile/follow/followers/Followers.jsx
  src/pages/profile/follow/followers/followerList.style.js
  src/pages/profile/follow/followers/followers.style.js
  src/pages/profile/follow/following/Following.jsx
  src/pages/profile/follow/following/FollowingList.jsx
  src/pages/profile/follow/following/following.style.js
  src/pages/profile/follow/following/followingList.style.js
Labels: fix, feat

#94 Fix: Profile 페이지 수정 및 ProfilePostList 컴포넌트 수정
  src/components/commons/topHeader/ProfileEditTopHeader.jsx
  src/components/commons/topHeader/TopHeader.jsx
  src/components/units/profile/ProfilePost/ProfilePostList.jsx
  src/components/units/profile/profileInfo/ProfileInfo.jsx
  src/components/units/profile/profileInfo/ProfileInfo.styles.js
  src/img/icon-more-vertical.svg
  src/pages/profile/userProfile/UserProfile.jsx
  src/pages/profile/userProfile/userProfile.styles.js
Labels: fix

#98 Feat: TopHeader 공통 컴포넌트 새로 추가
  src/components/commons/newTopHeader/NewTopHeader.jsx
  src/components/commons/newTopHeader/newTopHeader.style.js
Labels: feat

#100 Feat: API 이미지 전송 오류 해결
  src/pages/feed/post/postUpload/PostUpload.jsx
Labels: feat

#103 Feat: ProfileEdit 페이지 마크업 및 스타일 추가 프로필 수정 기능 구현 완료
  src/pages/profile/profileEdit/ProfileEdit.jsx
  src/pages/profile/profileEdit/profileEdit.style.js
Labels: feat

#108 Fix: NewTopHeader 공통 컴포넌트 수정
  src/components/commons/newTopHeader/NewTopHeader.jsx
  src/components/commons/newTopHeader/newTopHeader.style.js
Labels: fix

#105 Fix: ChatList, ChatRoom 페이지 새로운 TopHeader 적용 및 h1 태그 삭제
  src/pages/chat/chatList/ChatList.jsx
  src/pages/chat/chatRoom/ChatRoom.jsx
Labels: fix

#110 Fix: ProfileInfo 컴포넌트 follow unfollow 로직 수정
  src/components/units/profile/profileInfo/ProfileInfo.jsx
Labels: fix

#113 Fix: ProfileProduct, ProfilePost, ProfileGallery 컴포넌트 수정 및 UserProfile 페이지 TopHeader 변경
  src/components/units/profile/ProfilePost/ProfilePost.jsx
  src/components/units/profile/ProfilePost/ProfilePost.styles.js
  src/components/units/profile/ProfilePost/ProfilePostGallery.jsx
  src/components/units/profile/ProfileProduct/ProfileProductList.jsx
  src/pages/profile/userProfile/UserProfile.jsx
Labels: fix

#109 Feat: 수수마켓 피드 페이지 구현
  src/pages/feed/post/Post.jsx
Labels: feat

#111 99 feat 팔로우 팔로잉 기능구현
  src/components/commons/topHeader/SearchTopHeader.jsx
  src/pages/feed/search/Search.jsx
  src/pages/profile/follow/followers/FollowerList.jsx
  src/pages/profile/follow/followers/Followers.jsx
  src/pages/profile/follow/followers/addFollowAPI.js
  src/pages/profile/follow/followers/deleteFollowAPI.js
  src/pages/profile/follow/followers/followerAPI.js
  src/pages/profile/follow/followers/followerList.style.js
  src/pages/profile/follow/following/Following.jsx
  src/pages/profile/follow/following/FollowingList.jsx
  src/pages/profile/follow/following/followingAPI.js
  src/pages/profile/follow/following/followingList.style.js
Labels: fix, feat

#114 Feat: Post Upload 페이지 기능 api 업로드 문제 해결
  src/pages/feed/post/postUpload/PostUpload.jsx
Labels: feat

#117 18 feat 회원가입 page 추가
  src/pages/signup/profileSetting/ProfileSetting.jsx
Labels: feat

#122 112 feat post detail 페이지 구현
  src/pages/feed/post/postDetail/PostDetail.jsx
Labels: feat

#123 Refactor: debounce lodash라이브러리 이용하는 것으로 리팩토링
  src/library/useDebounce.js
  src/pages/feed/search/Search.jsx
Labels: fix, feat

#124 Feat: Post Edit 페이지 구현
  src/pages/feed/post/postEdit/PostEdit.jsx
Labels: feat

#126 Feat: 업로드 버튼 클릭 시 profile 페이지로 이동
  src/pages/feed/post/postEdit/PostEdit.jsx
Labels: feat

#132 Fix: NewTopButton 공통 컴포넌트 스타일 수정 및 Button 공통 컴포넌트 active 효과 적용
  src/components/commons/button/Button.jsx
  src/components/commons/newTopHeader/newTopHeader.style.js
  src/img/no-image.png
  src/pages/drawing/darwing.styles.js
Labels: chore, fix

#134 Feat: 상세페이지, 수정페이지, 업로드페이지 link 항목 전부 description으로 수정 완료, detail 페이지…
  src/pages/feed/product/productDetail/ProductDetail.jsx
  src/pages/feed/product/productEdit/ProductEdit.jsx
  src/pages/feed/product/productUpload/ProductUpload.jsx
Labels: feat

#136 Feat: imgValidation library 추가
  src/library/imgValidation.js
Labels: feat

#138 Fix: 129 fix 자기가 개발한 페이지 최종 확인
  src/components/units/profile/ProfilePost/ProfilePost.jsx
  src/components/units/profile/ProfilePost/ProfilePost.styles.js
  src/components/units/profile/ProfilePost/ProfilePostGallery.jsx
  src/components/units/profile/ProfilePost/ProfilePostGalleryList.jsx
  src/components/units/profile/ProfilePost/ProfilePostList.jsx
  src/components/units/profile/ProfileProduct/ProfileProductList.jsx
  src/components/units/profile/profileInfo/ProfileInfo.jsx
  src/components/units/profile/profileInfo/ProfileInfo.styles.js
  src/pages/chat/chatList/ChatList.jsx
  src/pages/chat/chatRoom/ChatRoom.jsx
  src/pages/chat/chatRoom/ChatRoom.style.js
  src/pages/drawing/Drawing.jsx
  src/pages/drawing/darwing.styles.js
  src/pages/feed/post/Post.jsx
  src/pages/profile/profileEdit/ProfileEdit.jsx
  src/pages/profile/profileEdit/profileEdit.style.js
  src/pages/profile/userProfile/UserProfile.jsx
Labels: chore, fix, feat

#140 Fix: post 페이지에서 feed 목록 post.image 데이터가 null 나오는 오류 수정
  src/components/units/profile/ProfilePost/ProfilePostList.jsx
Labels: fix

#141 131 fix 개발한 페이지 최종 확인
  src/pages/feed/post/Post.jsx
  src/pages/feed/post/postDetail/PostDetail.jsx
  src/pages/feed/post/postEdit/PostEdit.jsx
  src/pages/feed/post/postUpload/PostUpload.jsx
Labels: fix

#144 Fix: ProfilePostList 컴포넌트 post.image 조건부 렌더링 제거
  src/components/units/profile/ProfilePost/ProfilePostList.jsx
Labels: fix

#146 133 fix 자기가 개발한 페이지 최종확인
  src/pages/feed/product/productDetail/ProductDetail.jsx
  src/pages/feed/product/productDetail/productDetail.style.js
  src/pages/feed/product/productEdit/ProductEdit.jsx
  src/pages/feed/product/productEdit/productEdit.style.js
  src/pages/feed/product/productUpload/ProductUpload.jsx
  src/pages/feed/product/productUpload/productUpload.style.js
Labels: chore, fix

#145 Fix: 팔로워리스트에서 자기자신은 팔로워 버튼 disabled 처리
  src/pages/profile/follow/followers/FollowerList.jsx
  src/pages/profile/follow/followers/Followers.jsx
Labels: fix

#149 148 feat post detail 댓글 post 기능 수정
  src/pages/feed/post/postDetail/PostDetail.jsx
  src/pages/feed/post/postDetail/postDetail.style.js
  src/pages/feed/post/postEdit/PostEdit.jsx
  src/pages/feed/post/postUpload/PostUpload.jsx
Labels: fix, feat

#154 Fix: ProfileInfo 컴포넌트, UserProfile 페이지 useCallback 적용 및 오류 수정, FollowerList, FolloweringList 스타일 수정
  src/components/units/profile/profileInfo/ProfileInfo.jsx
  src/pages/profile/follow/followers/followerList.style.js
  src/pages/profile/follow/following/followingList.style.js
  src/pages/profile/userProfile/UserProfile.jsx
Labels: fix

#155 Fix: FollowerList 페이지 유저 프로필 이미지 정상적으로 출력 되지 않는 오류 수정
  src/pages/profile/follow/followers/FollowerList.jsx
Labels: fix

#164 Chore: ReadMe 핵심기능 및 코드 제목 수정
  README.md
Labels: fix
